<cntl name="gnb">
	$scope.projectName = 'default-project-name';
	$scope.onData = function(obj){
		$scope.projectName = obj.project;
		$($elm).find("[name='navbar']").html($scope.makeItems(obj.items));
	};
	$scope.makeItems = function(its){
		return 'hhh';
	};
	$scope.onClick = function(msg){
		alert('hi!----' + msg);
	}
	$scope.Data = [
		1, 5, 3, 10, 6, 7
	];
</cntl>

<gnb class="container">
	<div class="navbar-header">
		<a class="navbar-brand" href="#" onclick="$sj:scope.onClick('hello message')">{{projectName}}</a>
	</div>
	<div name="navbar" class="navbar-collapse collapse" data="$sj:ctx.scope.Data">
	<!-- 
		<ul class="nav navbar-nav">
			<li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
                	<li><a href="#">Another action</a></li>
                	<li><a href="#">Something else here</a></li>
                	<li role="separator" class="divider"></li>
                	<li class="dropdown-header">Nav header</li>
                	<li><a href="#">Separated link</a></li>
                	<li><a href="#">One more separated link</a></li>
              	</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
		</ul>
	 -->
	 kkkkk
	</div><!--/.nav-collapse -->
</gnb>
