<cntl name="gnb">
	ctx.projectName = 'default-project-name';
	ctx.onData = function(obj){
		console.log('111111111111');
		ctx.projectName = obj.project;
		console.log('22222');
		el("[name='navbar']").html(ctx.makeItems(obj.items));
		console.log('3333333333');
	};
	ctx.makeItems = function(its){
		console.log('44444444');
		return 'hhh';
	};
</cntl>

<gnb class="container">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">{{projectName}}</a>
	</div>
	<div name="navbar" class="navbar-collapse collapse">
	<!-- 
		<ul class="nav navbar-nav">
			<li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
                	<li><a href="#">Another action</a></li>
                	<li><a href="#">Something else here</a></li>
                	<li role="separator" class="divider"></li>
                	<li class="dropdown-header">Nav header</li>
                	<li><a href="#">Separated link</a></li>
                	<li><a href="#">One more separated link</a></li>
              	</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
		</ul>
	 -->
	 kkkkk
	</div><!--/.nav-collapse -->
</gnb>
